### ISSUE TITLE
Navbar Component

### ISSUE THREAD

**Issue by Hellrungj** [nashvillefcc/UndergroundJS-Website#1]
# Navbar Component
Difficulty Points: 5

## User Story
As an attendee, I want to navigate the site so that I can be able to find the information I need to determine whether or not I want to attend. 

## Acceptance Criteria:
- [x] I have the option of these pages:
   - [x] Home
   - [x] About
   - [x] Speakers
   - [x] Venue
   - [x] Sponsors
   - [x] FAQ
   - [x] Contact
- [x] I can see which page I'm on by the color difference (active state).
- [x] I can see which pages are available (hover state).

Definition of Done: Can the attendee navigate to the information they need?

**Comment by Hellrungj** [comment]
The following are UI/UX designs of the navbar.
![navbar-desktop](https://user-images.githubusercontent.com/8736564/75842263-799c0600-5d95-11ea-8222-595a7d50dbd4.png)
![navbar-mobile-landing](https://user-images.githubusercontent.com/8736564/75842267-7bfe6000-5d95-11ea-838d-23ffe20cc8ad.jpg)
![menu-mobile](https://user-images.githubusercontent.com/8736564/75842270-7d2f8d00-5d95-11ea-998e-a215c0beace3.png)

**Comment by lapinell** [comment]
Desktop
- [x] Menu top and bottom margin needs to be equal
- [x] Logo left margin needs to exist

Overall:
- [ ] border around mobile menu

Mobile Menu:
- [ ] Add "hover" orange to the background
